// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package dbgen

import (
	"context"
)

type Querier interface {
	InsertOrderProduct(ctx context.Context, arg InsertOrderProductParams) error
	InsertPurchaseHistory(ctx context.Context, arg InsertPurchaseHistoryParams) error
	OrderProductFindById(ctx context.Context, id string) (OrderProduct, error)
	ProductFindById(ctx context.Context, id string) (Product, error)
	ProductFindByIds(ctx context.Context, ids []string) ([]Product, error)
	PurchaseHistoryFindById(ctx context.Context, id string) (Order, error)
	UpsertProduct(ctx context.Context, arg UpsertProductParams) error
	UpsertUser(ctx context.Context, arg UpsertUserParams) error
	UserFindById(ctx context.Context, id string) (User, error)
}

var _ Querier = (*Queries)(nil)
