definitions:
  health_handler.HealthResponse:
    properties:
      status:
        type: string
    type: object
  user.getUserResponse:
    properties:
      users:
        $ref: '#/definitions/user.userResponseModel'
    type: object
  user.userResponseModel:
    properties:
      address:
        type: string
      email:
        type: string
      first_name:
        type: string
      id:
        type: string
      last_name:
        type: string
      phone_number:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: 説明
  license:
    name: ライセンス(必須)
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: アプリケーション名
  version: バージョン(1.0)
paths:
  /v1/health:
    get:
      consumes:
      - application/json
      description: ヘルスチェック
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/health_handler.HealthResponse'
      summary: ヘルスチェック
      tags:
      - health
  /v1/users/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.getUserResponse'
      summary: ユーザーを取得する
      tags:
      - users
swagger: "2.0"
