version: "3"
volumes:
  db-store:
    driver: local

services:
  # データベース
  db:
    image: mysql:latest
    volumes:
      - type: volume
        source: db-store
        target: /var/lib/mysql
        volume:
          nocopy: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: code_kakitai
      TZ: Asia/Tokyo
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    command: --collation-server=utf8mb4_general_ci

  # redis
  redis:
    image: redis:6.0-alpine3.18
    ports:
      - 6380:6379

  # バックエンドサーバー
  app:
    build:
      context: .
      dockerfile: ./ops/docker/app/Dockerfile
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: ./
        target: /data
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - db
      - redis
