version: "3"
volumes:
  db-store:
    driver: local
  test-db-store:
    driver: local

services: 
  db:
    image: mysql:latest
    volumes:
      - type: volume
        source: db-store
        target: /var/lib/mysql
        volume:
          nocopy: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: code_kakitai
      TZ: Asia/Tokyo
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    command: --collation-server=utf8mb4_general_ci
  test_db:
    image: mysql:latest
    volumes:
      - type: volume
        source: test-db-store
        target: /var/lib/mysql
        volume:
          nocopy: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: code_kakitai
      TZ: Asia/Tokyo
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    command: --collation-server=utf8mb4_general_ci
  app:
    build:
      context: .
      dockerfile: ./ops/docker/app/Dockerfile
    tty: true 
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
    depends_on:
      - db
      - test_db
