// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0

package dbgen

import (
	"database/sql"
	"time"
)

type User struct {
	ID          string         `json:"id"`
	Email       string         `json:"email"`
	Password    string         `json:"password"`
	PhoneNumber sql.NullString `json:"phone_number"`
	Name        sql.NullString `json:"name"`
	// 郵便番号
	PostalCode sql.NullString `json:"postal_code"`
	// 都道府県
	Prefecture sql.NullString `json:"prefecture"`
	// 市区町村
	City sql.NullString `json:"city"`
	// 住所詳細
	AddressExtra sql.NullString `json:"address_extra"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}
