// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0

package dbgen

import (
	"time"
)

type User struct {
	ID          string `json:"id"`
	Email       string `json:"email"`
	Password    string `json:"password"`
	PhoneNumber string `json:"phone_number"`
	Name        string `json:"name"`
	// 郵便番号
	PostalCode string `json:"postal_code"`
	// 都道府県
	Prefecture string `json:"prefecture"`
	// 市区町村
	City string `json:"city"`
	// 住所詳細
	AddressExtra string    `json:"address_extra"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}
