// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0
// source: user.sql

package dbgen

import (
	"context"
)

const userFindById = `-- name: UserFindById :one
SELECT
   id, email, password, phone_number, name, postal_code, prefecture, city, address_extra, created_at, updated_at
FROM
   users
WHERE id = ?
`

func (q *Queries) UserFindById(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, userFindById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.PhoneNumber,
		&i.Name,
		&i.PostalCode,
		&i.Prefecture,
		&i.City,
		&i.AddressExtra,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
