name: CI/CD

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
    paths:
      - 'app/**'


jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup
        run : |
          make up
      - name: test
        run: make test

