name: CI/CD

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
    paths:
      - 'app/**'


jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version-file: app/go.mod
          cache: true
          cache-dependency-path: app/go.sum

      - name: setup test-db
        run : |
          make up-test-db

      - name: test
        run: |
          cd app && go vet ./... && go test ./...

